codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  show_carryforward_flags: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 1%
        informational: false
  precision: 2
  round: down
  range: 70..100

ignore:
  - "**/*.test.ts"
  - "tests/**"
